name: Android CI

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Java JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Signed app bundle
        path: app/build/outputs/apk
